//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveCodeAnalyzer.Library {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiveCodeAnalyzer.Library.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LiveCodeAnalyzer - The Identifier &apos;{0}&apos; should have valid comments.
        /// </summary>
        internal static string AnalyzerClassMissingCommentsDescription {
            get {
                return ResourceManager.GetString("AnalyzerClassMissingCommentsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LiveCodeAnalyzer - The class name should have valid comments.
        /// </summary>
        internal static string AnalyzerClassMissingCommentsTitle {
            get {
                return ResourceManager.GetString("AnalyzerClassMissingCommentsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LiveCodeAnalyzer - The Identifier should start with uppercase..
        /// </summary>
        internal static string AnalyzerDescription {
            get {
                return ResourceManager.GetString("AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LiveCodeAnalyzer - The Identifier &apos;{0}&apos; should start with uppercase..
        /// </summary>
        internal static string AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LiveCodeAnalyzer - The Identifier &apos;{0}&apos; should have valid comments.
        /// </summary>
        internal static string AnalyzerMethodMissingCommentsDescription {
            get {
                return ResourceManager.GetString("AnalyzerMethodMissingCommentsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LiveCodeAnalyzer - The method name should have valid comments.
        /// </summary>
        internal static string AnalyzerMethodMissingCommentsTitle {
            get {
                return ResourceManager.GetString("AnalyzerMethodMissingCommentsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LiveCodeAnalyzer - Please validate method &apos;{0}&apos; parameters..
        /// </summary>
        internal static string AnalyzerParameterValidateDescription {
            get {
                return ResourceManager.GetString("AnalyzerParameterValidateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LiveCodeAnalyzer - Please validate method &apos;{0}&apos; parameters..
        /// </summary>
        internal static string AnalyzerParameterValidateTitle {
            get {
                return ResourceManager.GetString("AnalyzerParameterValidateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LiveCodeAnalyzer - The Identifier contains sensitive information..
        /// </summary>
        internal static string AnalyzerSensitiveInfoDescription {
            get {
                return ResourceManager.GetString("AnalyzerSensitiveInfoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LiveCodeAnalyzer - The Identifier contains sensitive information..
        /// </summary>
        internal static string AnalyzerSensitiveInfoTitle {
            get {
                return ResourceManager.GetString("AnalyzerSensitiveInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LiveCodeAnalyzer - The Identifier contains lowercase letters.
        /// </summary>
        internal static string AnalyzerTitle {
            get {
                return ResourceManager.GetString("AnalyzerTitle", resourceCulture);
            }
        }
    }
}
