PasswordDeriveBytes:
  namespace: System.Security.Cryptography
  className: PasswordDeriveBytes
  member: method
  name: .ctor
  passwordArguments: 0
  localePass: SG0015

NetworkCredential:
  namespace: System.Net
  className: NetworkCredential
  member: method
  name: .ctor
  passwordArguments: 1
  localePass: SG0015
